# Generated by Django 3.2 on 2021-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_mpi_job_job_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpi_job',
            name='stdin_filepath',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
